
[[dependencies]]
  branch = "master"
  name = "k8s.io/apimachinery"

[[dependencies]]
  name = "k8s.io/client-go"
  version = "^2.0.0"

[[dependencies]]
  branch = "master"
  name = "k8s.io/kubernetes"
