name: release

on:
  release:
    types: [created]

jobs:
  docker:
    environment: deployment
    runs-on: ubuntu-latest
    steps:
      - name: qemu setup
        uses: docker/setup-qemu-action@v1
      - name: docker buildx setup
        uses: docker/setup-buildx-action@v1
      - name: docker login
        uses: docker/login-action@v1
        with:
          username: brianberzins
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: build and publish
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: |
            brianberzins/pod-reaper:lastest
            brianberzins/pod-reaper:alpha
