name: test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: golang setup
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: test
      run: |
        go build -v ./...
        go test -v ./...

  docker:
    runs-on: ubuntu-latest
    steps:
      - name: qemu setup
        uses: docker/setup-qemu-action@v1
      - name: docker buildx setup
        uses: docker/setup-buildx-action@v1
      - name: docker build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
